#ifndef INC_VERSION_H_
#define INC_VERSION_H_

#define LOOPCTR_VER_MAJOR   0
#define LOOPCTR_VER_MINOR   1
#define LOOPCTR_VER_PATCH   0

#define LOOPCTR_VERSION     (LOOPCTR_VER_MAJOR*10000 + LOOPCTR_VER_MINOR*100 + LOOPCTR_VER_PATCH)

#endif /* INC_VERSION_H_ */
